project:
  type: website
  output-dir: docs
author:
  - Helder Lira
website:
  title: "Projeto de Mestrado"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual