---
title: "Variáveis EMA"
author: "Helder Lira"
date: "2025-05-20"
format:
  html:
    css: table.css
---

```{r}
#| label: knitr options
#| echo: false

knitr::opts_chunk$set(
  results = 'asis',
  echo = FALSE,
  warning = FALSE,
  tidy = FALSE,
  message = FALSE,
  fig.align = 'center',
  out.width = "100%"
)
options(knitr.table.format = "html")
```

# Resumo

This document contains a technical overview of the assessment protocol used in the High Risk Cohort (Salum et al., 2015). This cohort study follows a sample of 2511 youths (inclusion age range: 6-14y) with high risk for mental disorder incidence.

The third assessment moment is ongoing, starting in 2018. Participants and parents or relatives were asked to install and interact with our in-house Electronic Momentary Assessment (EMA) software. This application conforms to ethical norms and its used was approved by national and regional ethical research committees, it also obeys privacy and user right policies enforced by Google and Apple distribution server stores.

Our application gathers input through screen prompted self-report items. Users consent to every step of data collection.

Our protocol measures human behavior using multiple targets, such as: sleep patterns and quality, self-reported behavior, subjective emotional perception, composition of environmental surroundings, average dislocation by step count and social media activity.

# Variáveis de Identificação (registradas uma única vez)

| Variável | Descrição |
|----|----|
| **Subjectid** | ID numérico do participante |
| **EMA_name** | Nome da criança/adolescente no app |
| **EMA_mother**, **EMA_birth** | Nome da mãe biológica e data de nascimento |
| **EMA_resp**, **EMA_resp_other** | Nome e grau de parentesco do responsável que responderá as rodadas dos pais |

# Self Report Evaluation

As perguntas de Sono são feitas apenas uma vez por dia pela manhã. As outras são feitas por 28 dias (após avaliação clínica), 4 vezes por dia.

| Construct | Variable Name | item | Levels | Answer format |
|----|----|----|----|----|
| Sleep | SEMA_int_sleep | Que horas você pegou no sono ontem à noite? | hh:mm ou Não sei | Either Time or Missing data |
| Sleep | SEMA_int_wake | Que horas você acordou hoje pela manhã? | hh:mm ou Não sei | Either Time or Missing data |
| Sleep | SEMA_int_quali | Como você classificaria a qualidade do seu sono? | \(1\) Muito ruim, (2) Ruim, (3) Razoável, (4) Boa, (5) Muito boa | Likert (1-5): |
| Environment | SEMA_int_alone | Você está sozinho ou com outras pessoas? | \(1\) Sozinho, (2) Acompanhado |  |
| Environment | SEMA_int_natu1 | Você está em um lugar aberto ou fechado neste momento? | \(1\) Lugar aberto, (2) Lugar Fechado | Pseudocode for randomization\* of daily question time |
| Environment | SEMA_int_natu2 | Você está em contato com a natureza (exemplo: árvores, grama, etc.)? | \(1\) Sim, (2) Não | Binary: Dichotomic: Integer |
| Mood | SEMA_int_thumbs | Como você se sente neste momento... | \(1\) 3 thumbs UP (cor verde), (2) 2 thumbs UP (cor verde), (3) 1 thumb UP (cor verde), (4) 1 thumb UP (verde) e 1 thumb DOWN (vermelho); (5) 1 thumb DOWN (cor vermelha), (6) 2 thumbs DOWN (cor vermelha) e (7) 3 thumbs DOWN (cor vermelha) | Bidirectional Likert (1-7) scale |
| Mood | SEMA_int_mood1 | Feliz vs. Triste | \(1\) Muito feliz, (2) Feliz, (3) Um pouco feliz, (4) Neutro, (5) Um pouco triste, (6) Triste, (7) Muito triste | Bidirectional Likert (1-7) scale |
| Mood | SEMA_int_mood2 | Relaxado vs. Ansioso | \(1\) Muito relaxado, (2) Relaxado, (3) Um pouco relaxado, (4) Neutro, (5) Um pouco ansioso, (6) Ansioso, (7) Muito ansioso | Bidirectional Likert (1-7) scale |
| Mood | SEMA_int_mood3 | Desanimado vs. Animado | \(1\) Muito animado, (2) Animado, (3) Um pouco animado, (4) Neutro, (5) Um pouco desanimado, (6) Desanimado, (7) Muito Desanimado | Bidirectional Likert (1-7) scale |
| Mood | SEMA_int_mood4 | Energético vs. Cansado | \(1\) Muito energético, (2) Energético, (3) Um pouco energético, (4) Neutro, (5) Um pouco cansado, (6) Cansado, (7) Muito cansado | Bidirectional Likert (1-7) scale |
| Mood | SEMA_int_mood5 | Calmo vs. Irritado | \(1\) Muito calmo, (2) Calmo, (3) Um pouco calmo, (4) Neutro, (5) Um pouco irritado, (6) Irritado, (7) Muito irritado | Bidirectional Likert (1-7) scale |
|  |  |  |  |  |

# Parent-Report Evaluation – Intensive

Diariamente por 28 dias após avaliação clínica (2x/dia). As variáveis são apresentadas em 4 Domínios principais do respondente em relação a criança/adolescente: Sono, "Contato", "Emotional Behaviors" e "Conduct Behaviors".

| Construct | Variable Name | Item | Levels | Example | period | Time of day |
|----|----|----|----|----|----|----|
| Sleep | EMA_int_sleep | Aproximadamente, que horas (EMA_name) pegou no sono ontem à noite? | hh:mm  ou Não sei | 23:00 | morning | 09:00 |
| Sleep | EMA_int_wakeint | Aproximadamente, que horas (EMA_name) acordou hoje pela manhã? | hh:mm ou Não Sei | 08:00 | morning | 09:00 |
|  | EMA_int_contato | Aproximadamente, quanto tempo você passou com (EMA_name) hoje? | hh:mm | 1h 30 min | night | 21:00 |
| Emotional behaviors | SDQ_int_somatic | Ao longo do dia de hoje, (EMA_name)..Queixou-se de dor de cabeça, dor de barriga ou enjôo | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Emotional behaviors | SDQ_int_worries | Teve muitas preocupações | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Emotional behaviors | SDQ_int_unhappy | Pareceu triste, desanimado, choroso | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Emotional behaviors | SDQ_int_clingy | Ficou inseguro e facilmente perdeu a confiança em si mesmo | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Emotional behaviors | SDQ_int_afraid | Teve muitos medos, assustou-se facilmente | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Conduct behaviors | SDQ_int_tantrums | Teve acessos de raiva ou crises de birra | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Conduct behaviors | SDQ_int_obeys | Foi obediente, fez o que os adultos lhe pediram | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Conduct behaviors | SDQ_int_fights | Brigou com outras crianças ou as amendrontou | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Conduct behaviors | SDQ_int_lies | Enganou ou mentiu | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |
| Conduct behaviors | SDQ_int_steals | Roubou coisas de casa, da escola ou de outros lugares | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Falso | night | 21:00 |

# Self-Report Evaluation – Non-intensive

Semanalmente por 1 ano (após o EMA intensivo).

| Construct | Variable Name | Item | Levels | Answer format | Example | Time of day |
|----|----|----|----|----|----|----|
| Mood | SEMA_thumbs | Como você se sente neste momento... | \(1\) 3 thumbs UP (cor verde), (2) 2 thumbs UP (cor verde), (3) 1 thumb UP (cor verde), (4) 1 thumb UP (verde) e 1 thumb DOWN (vermelho), (5) 1 thumb DOWN (cor vermelha), (6) 2 thumbs DOWN (cor vermelha), (7) 3 thumbs DOWN (cor vermelha) | Bidirectional Likert (1-7) scale | 2 thumbs UP (cor verde) |  |
| Sleep | SEMA_sleep | EM MÉDIA, que horas você pegou no sono na maioria dos dias dessa última semana? | hh:mm ou Não Sei | Either Time or Missing data | 21:00 | 18:00 |
| Sleep | SEMA_wake | EM MÉDIA, que horas você acordou na maioria dos dias dessa última semana? | hh:mm ou Não Sei | Either Time or Missing data | 08:00 | 18:00 |
| Sleep | SEMA_quali | Como você classificaria a qualidade do seu sono nessa última semana? | \(1\) Muito ruim, (2) Ruim, (3) Razoável, (4) Boa, (5) Muito boa | Bidirectional Likert (1-5) scale | Ruim | 18:00 |
| Enviroment | SEMA_natu | Quantos dias você ficou em contato com a natureza (exemplo: árvores, grama, etc.) nessa última semana? | \(1\) Nenhum dia, (2) 1 dia, (3) 2 dias, (4) 3 dias, (5) 4 dias, (6) 5 dias, (7) 6 dias, (8) Todos os dias | Bidirectional Likert (1-5) scale | \(1\) nenhum dia | 18:00 |
| Emotional behaviors | SSDQ_somatic | Ao longo dessa última semana...Tive dor de cabeça, dor de barriga ou enjôo | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SSDQ_worries | Tive muitas preocupações | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SSDQ_unhappy | Estava triste, desanimado, choroso | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SSDQ_clingy | Fiquei inseguro e facilmente perdi a confiança em mim | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SSDQ_afraid | Tive muitos medos, assustei-me facilmente | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SSDQ_tantrums | Tive acessos de raiva ou crises de birra | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SSDQ_obeys | Fui obediente, fiz tudo o que os adultos me pediram | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SSDQ_fights | Briguei com outras crianças ou as amendrontei | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SSDQ_lies | Enganei ou menti | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SSDQ_steals | Roubei coisas de casa, da escola ou de outros lugares | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |

# Parent-Report Evaluation (Non-intensive)

A cada 35 dias por um ano (após EMA intensivo).

| Construct | Variable Name | Item | Levels | Answer format | Example | Time of day |
|----|----|----|----|----|----|----|
| Sleep | EMA_sleep | EM MÉDIA, que horas (EMA_name) pegou no sono na maioria dos dias dessa semana? | hh:mm ou Não Sei | Either Time or Missing data | 21:00 | 18:00 |
| Sleep | EMA_wake | EM MÉDIA, que horas (EMA_name) acordou na maioria dos dias dessa semana? | hh:mm ou Não Sei | Either Time or Missing data | 08:00 | 18:00 |
| Sleep | EMA_contato | Quanto tempo você passou com (EMA_name) nessa semana? | \(1\) Nenhum dia, (2) 1 dia, (3) 2 dias, (4) 3 dias, (5) 4 dias, (6) 5 dias, (7) 6 dias, (8) Todos os dias | Ordered factor \[1…6,6+\] | \(1\) nenhum dia | 18:00 |
| Emotional behaviors | SDQ_somatic | Ao longo dessa semana (EMA_name Queixou-se de dor de cabeça, dor de barriga ou enjôo | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SDQ_worries | Teve muitas preocupações | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SDQ_unhappy | Pareceu triste, desanimado, choroso | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SDQ_clingy | Ficou inseguro e facilmente perdeu a confiança em si mesmo | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Emotional behaviors | SDQ_afraid | Teve muitos medos, assustou-se facilmente | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SDQ_tantrums | Teve acessos de raiva ou crises de birra | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SDQ_obeys | Foi obediente, fez o que os adultos lhe pediram | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SDQ_fights | Brigou com outras crianças ou as amendrontou | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SDQ_lies | Enganou ou mentiu | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
| Conduct behaviors | SDQ_steals | Roubou coisas de casa, da escola ou de outros lugares | \(1\) Falso, (2) Mais ou menos verdadeiro, (3) Verdadeiro | Bidirectional Likert (1-3) scale | Falso | 18:00 |
